version: "3.1"

services:
  db:
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: teste
      MYSQL_DATABASE: bank
      MYSQL_USERNAME: lu
      MYSQL_PASSWORD: 123456
    ports:
      - 3306:3306
    volumes:
      - "./bank.sql:/docker-entrypoint-initdb.d/bank.sql"

  app-lumen:
    image: bank:0.1
    build: .
    ports:
      - 8000:8000
