version: "3.1"

services:
  db:
    image: mysql:5.7

    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=bank
      - MYSQL_USERNAME=lu
      - MYSQL_PASSWORD=123456
    ports:
      - 3306:3306
    volumes:
      - "./bank.sql:/docker-entrypoint-initdb.d/bank.sql"

  app:
    image: bank:0.1
    build: .
    ports:
      - 8000:8000
    environment:
      - APP_NAME=Lumen
      - APP_ENV=local
      - APP_KEY=
      - APP_DEBUG=true
      - APP_URL=http://localhost
      - APP_TIMEZONE=UTC
      - LOG_CHANNEL=stack
      - LOG_SLACK_WEBHOOK_URL=
      - DB_CONNECTION=mysql
      - DB_HOST=db
      - DB_PORT=3306
      - DB_DATABASE=bank
      - DB_USERNAME=root
      - DB_PASSWORD=root
      - CACHE_DRIVER=file
      - QUEUE_CONNECTION=sync
    depends_on:
      - db
